name: CI & Release

on:
  pull_request:
    branches:
      - "main"
      - "debank"
      - "merlin"
  release:
    types:
      - created
  workflow_dispatch:

env:
  REGISTRY: 294354037686.dkr.ecr.ap-northeast-1.amazonaws.com
  IMAGE: blockchain-cdk-erigon
  DOCKERFILE: Dockerfile.debian

jobs:
  make-image:
    runs-on: [self-hosted, linux, amd64]
    steps:
      - name: Checkout dettack
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.RELEASE_MANAGER_APP_ID }}
          private_key: ${{ secrets.RELEASE_MANAGER_APP_SECRET }}

      - name: Set env for PR
        if: github.event_name == 'pull_request'
        run: |
          echo "REVISION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Set env for Release
        if: github.event_name == 'release'
        run: |
          echo "REVISION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set env for Manual Dispatch
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "REVISION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build image and push to ECR
        uses:  docker/build-push-action@v5
        with:
          file: ${{ env.DOCKERFILE }}
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ env.REVISION }}
          build-args: ACCESS_TOKEN=${{ steps.generate-token.outputs.token }}
          provenance: false

      - name: Lark Notification
        continue-on-error: true
        run: |
          notiv3 "Blockchain client cdk-erigon's image pushed 🎉" ${${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ env.REVISION }}